spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf8
        username: root
        password: password
